### ISSUE TITLE
Having the issue with Module Installation

### ISSUE THREAD

**Issue by soheilAppear** [apple/ml-quant#1]
I have this error when I wanted to run the code:

**from quant.common.compute_platform import LocalComputePlatform
ModuleNotFoundError: No module named 'quant'**

anyone know how can I fix it?

**Comment by tuzhucheng** [comment]
Hi Soheil, have you done `flit install -s` per the instructions in the [README.md](https://github.com/apple/ml-quant/blob/master/README.md)?

Here are our recommended installation instructions. **Please make sure to use Python 3.6 (or a later version) for installation and running the code.**

```bash
# Go to repo
cd <path/to/quant>
# Create virtual environment ...
python -m venv .venv
# ... and activate it
source .venv/bin/activate
# Upgrade to the latest versions of pip and wheel
pip install -U pip wheel
pip install -r requirements.txt
```

Then install quant with these commands:

```
pip install flit
flit install -s
```

**Comment by soheilAppear** [comment]
Hey. Thanks for the reply. I tried to do that before opening this issue topic. However, I got this error when I used that coomand with  -s: 

Extras to install for deps 'all': {'test', '.none', 'doc'}  I-flit.install
Installing requirements                                 I-flit.install
Symlinking .\quant -> c:\users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\Lib\site-packages\quant  I-flit.install
Traceback (most recent call last):
  File "c:\users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\Scripts\flit.exe\__main__.py", line 7, in <module>
  File "c:\users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\lib\site-packages\flit\__init__.py", line 188, in main
    pth=args.pth_file).install()
  File "c:\users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\lib\site-packages\flit\install.py", line 407, in install
    self.install_directly()
  File "c:\users\sohei\.conda\envs\env_pytorch\envs\env_pytorch2\lib\site-packages\flit\install.py", line 305, in install_directly
    os.symlink(osp.abspath(self.module.path), dst)
OSError: symbolic link privilege not held


Then I tried to install it without -s and it installed correctly. However, still I'm not able to use the library.

**Comment by soheilAppear** [comment]
It shows me the same error.

**Comment by soheilAppear** [comment]
I think i fixed the issue by running the command with Administration access. That was the issue to create the symboling link!
